name: Harold Lu
author: Harold Lu
baseurl: https://harold-lu.github.io
description: Curriculum vitae
github: http://www.github.com/harold-lu
linkedin: https://www.linkedin.com/in/harold-lu/
email: mailto:harold.lu123@gmail.com

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
