name: Harold Lu
author: Harold Lu
baseurl: https://haroldlu.com
description: Curriculum vitae
github: https://www.github.com/harold-lu
linkedin: https://www.linkedin.com/in/harold-lu/
email: mailto:harold.lu@carleton.ca

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
